"""Generate per-tool instruction files from one source.

Never hand-maintain these. Six instruction files edited by hand drift within a
week, and then each teammate's agent is following a different protocol -- which
is precisely the failure the registry exists to prevent, one level up.

PROTOCOL.md is the tool-agnostic source of truth. Everything else is derived.
"""

from __future__ import annotations

import os

from . import registry as rg
from .model import PHASES, PHASE_LABEL

PROTOCOL = '''# Storypole protocol

Tool-agnostic. This file is the source of truth; every agent instruction file
is generated from it by `storypole emit`. Do not edit those by hand.

## The registry

`features/` holds one markdown file per feature: frontmatter plus prose. Fields:

| Field | Meaning |
| --- | --- |
| `id` | `F-001`, stable forever |
| `title` | what a user would call the capability |
| `phase` | %(phases)s |
| `owner` | who is accountable; empty means unowned |
| `locked_by` / `locked_at` | exclusive claim, and when it was taken |
| `version` | this feature's own version, bumped freely |
| `depends_on` | ids this feature needs |
| `priority` | `p0`-`p3` |
| `smoke` | `pass` / `fail`; required to enter validation |
| `learning` | what you found out; required to leave validation |
| `retired_reason` | why it died |
| `expires` | kill date, for time-boxed spikes |

Body sections: Problem, Requirements, Acceptance criteria, Out of scope.

## The rules

1. **Read the current state first.** Pull the integration branch and run
   `storypole list` and `storypole check` before touching anything.
2. **Locks are exclusive.** A feature locked by someone else cannot be
   enhanced, bumped, advanced or retired by anyone but the holder. Never edit
   frontmatter by hand to get around this.
3. **Impact before bump.** `storypole bump` refuses until `storypole impact`
   has run against the feature's current state. Read the dependents; confirm
   their acceptance criteria still hold.
4. **Spec before code.** Amend requirements and bump the feature version first.
   If code lands first the PRD drifts into describing last month's prototype.
5. **Phase gates.** A feature enters a phase only when that phase's artifact
   exists: no development without an owner, acceptance criteria and an
   out-of-scope section; no validation without a passing smoke test and a
   current PRD; nothing leaves validation without a recorded learning.
6. **Additive, never a replacement.** Contribute a delta to the current head.
   Do not regenerate the prototype in your own style.
7. **Do not refactor code you did not come to change.** Not naming, not
   formatting, not "while I was in here."
8. **Changelog fragments.** Write a new file in `changelog.d/`. Never append to
   a shared changelog -- new files do not conflict; six people appending do.
9. **Release versions are assigned at release**, never on a branch.
10. **The PRD is generated.** Edit `features/` and `PRD-intro.md`; run
    `storypole prd build`. Resolve a PRD.md conflict by rebuilding.

## Commands

```
storypole list --available          what is free to pick up
storypole check                     registry health
storypole claim F-002 --as sam      take ownership
storypole lock F-002 --as sam       exclusive claim
storypole impact F-002 --as sam     required before bump
storypole bump F-002 --as sam       bump the feature version
storypole advance F-002 --as sam    move to the next phase (gated)
storypole smoke F-002 --result pass record a smoke test
storypole learn F-002 --text "..."  record what you found out
storypole drop F-002 --reason "..." retire it, with a reason
storypole prd build                 regenerate PRD.md
```

Every command takes `--json`. Exit codes: `0` proceed, `1` blocked.

## What this does not guarantee

Locks are a convention. The tool refuses the operation and a cooperating agent
honours it, but anyone can edit frontmatter by hand. For real enforcement use
CODEOWNERS on `features/` plus branch protection, so unauthorised changes are
blocked at merge rather than at the honour system.
'''

HEADER = ("<!-- GENERATED by `storypole emit` from PROTOCOL.md. "
          "Do not edit by hand; your changes will be overwritten. -->\n\n")

# AGENTS.md is the closest thing to a cross-tool standard, so it is the primary
# target and the others mostly point at it.
TARGETS = {
    "agents": ("AGENTS.md", "markdown"),
    "claude": ("CLAUDE.md", "markdown"),
    "cursor": (os.path.join(".cursor", "rules", "storypole.mdc"), "mdc"),
    "windsurf": (".windsurfrules", "plain"),
    "copilot": (os.path.join(".github", "copilot-instructions.md"), "markdown"),
    "gemini": ("GEMINI.md", "markdown"),
    "cline": (".clinerules", "plain"),
}

MDC_FRONTMATTER = "---\ndescription: Storypole contribution protocol\nalwaysApply: true\n---\n\n"


def render_protocol() -> str:
    return PROTOCOL % {"phases": " -> ".join(PHASES)}


def emit(root: str, targets: list | None = None) -> rg.Result:
    protocol_path = os.path.join(root, "PROTOCOL.md")
    body = render_protocol()
    with open(protocol_path, "w", encoding="utf-8") as fh:
        fh.write(body)
    written = ["PROTOCOL.md"]

    chosen = targets or list(TARGETS)
    unknown = [t for t in chosen if t not in TARGETS]
    if unknown:
        return rg.blocked("unknown target(s): %s" % ", ".join(unknown),
                          "Known targets: %s" % ", ".join(TARGETS))

    for name in chosen:
        rel, kind = TARGETS[name]
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path) or root, exist_ok=True)
        text = HEADER + body
        if kind == "mdc":
            text = MDC_FRONTMATTER + HEADER + body
        elif kind == "plain":
            text = HEADER.replace("<!-- ", "# ").replace(" -->", "") + body
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        written.append(rel)

    return rg.done("Wrote %s" % ", ".join(written), written=written)
