"""Generate PRD.md from PRD-intro.md plus the registry.

The PRD is generated, never hand-edited. That is what keeps it honest: it
cannot drift from the registry, and a merge conflict in PRD.md is resolved by
discarding both sides and rebuilding.
"""

from __future__ import annotations

import datetime as dt
import os
import re

from .model import PHASE_LABEL, PHASES, TERMINAL, Feature, phase_index
from . import registry as rg

GENERATED_NOTE = (
    "<!-- GENERATED BY storypole -- do not edit by hand.\n"
    "     Edit files in features/ and run: storypole prd build -->"
)


def demote_headings(body: str, levels: int = 2) -> str:
    """Push headings deeper so an embedded document does not flatten the
    outline it is embedded in -- but never inside a fenced code block, where a
    leading '#' is a comment."""
    out, fence = [], None
    for line in body.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            marker = stripped[:3]
            fence = None if fence == marker else (fence or marker)
            out.append(line)
            continue
        if fence is None and (m := re.match(r"^(#{1,6})(\s+)", line)):
            line = "#" * min(len(m.group(1)) + levels, 6) + m.group(2) + line[m.end():]
        out.append(line)
    return "\n".join(out)


def feature_section(feat: Feature, features: list) -> str:
    dependents = [f.id for f in features if feat.id in f.depends_on]
    meta = ["**Phase** %s" % PHASE_LABEL.get(feat.phase, feat.phase),
            "**Owner** %s" % (feat.owner or "_unassigned_"),
            "**Version** %s" % feat.version,
            "**Priority** %s" % feat.priority]
    if feat.locked_by:
        meta.append("**Locked by %s**" % feat.locked_by)
    lines = ["### %s -- %s" % (feat.id, feat.title), "", " · ".join(meta), ""]
    if feat.expires:
        lines += ["Spike, expires %s." % feat.expires, ""]
    if feat.depends_on:
        lines.append("Depends on: %s" % ", ".join(feat.depends_on))
    if dependents:
        lines.append("Depended on by: %s" % ", ".join(dependents))
    if feat.depends_on or dependents:
        lines.append("")
    if feat.phase == "retired" and feat.retired_reason:
        lines += ["> **Retired:** %s" % feat.retired_reason, ""]
    if feat.learning:
        lines += ["> **What we learned:** %s" % feat.learning, ""]
    lines += [demote_headings(feat.body).strip(), ""]
    return "\n".join(lines)


def render(root: str) -> str:
    features = rg.load_all(root)
    cfg = rg.load_config(root)
    intro_path = os.path.join(root, "PRD-intro.md")
    intro = open(intro_path, encoding="utf-8").read().strip() if os.path.exists(intro_path) else ""

    parts = [GENERATED_NOTE, "", "# Product requirements", ""]
    if cfg.get("repo_url"):
        parts += ["Repo: %s" % cfg["repo_url"], ""]
    if intro:
        # the intro is authored standalone, so its own H1 would collide with
        # the PRD title; drop it one level
        parts += [demote_headings(intro, 1), ""]

    parts += ["## Feature index", ""]
    if not features:
        parts += ["_No features yet. Run `storypole new --title ...`._", ""]
    else:
        parts += ["| ID | Feature | Phase | Owner | Version | Lock |",
                  "| --- | --- | --- | --- | --- | --- |"]
        for f in sorted(features, key=lambda f: (phase_index(f.phase), f.id)):
            parts.append("| %s | %s | %s | %s | %s | %s |" % (
                f.id, f.title, PHASE_LABEL.get(f.phase, f.phase), f.owner or "-",
                f.version, ("locked by %s" % f.locked_by) if f.locked_by else ""))
        parts.append("")

        counts = {}
        for f in features:
            if f.phase not in TERMINAL:
                counts[f.phase] = counts.get(f.phase, 0) + 1
        if counts:
            parts += ["_%s. WIP limit %s._" % (
                ", ".join("%d %s" % (counts[p], PHASE_LABEL[p].lower())
                          for p in PHASES if p in counts),
                cfg.get("wip_limit")), ""]

        for phase in PHASES:
            group = [f for f in features if f.phase == phase]
            if not group:
                continue
            parts += ["## %s" % PHASE_LABEL[phase], ""]
            if phase == "retired":
                parts += ["_Features we killed, and why. Read this before proposing "
                          "something that sounds new._", ""]
            for f in sorted(group, key=lambda f: f.id):
                parts.append(feature_section(f, features))

    parts += ["---", "", "Generated %s from %d feature file(s)."
              % (dt.date.today().isoformat(), len(features))]
    return "\n".join(parts).rstrip() + "\n"


def _strip_stamp(text: str) -> str:
    return re.sub(r"\nGenerated \d{4}-\d{2}-\d{2} from .*\n?$", "\n", text)


def build(root: str, out: str | None = None) -> rg.Result:
    target = out or os.path.join(root, "PRD.md")
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(render(root))
    return rg.done("Wrote %s" % target, path=target)


def check(root: str, out: str | None = None) -> rg.Result:
    target = out or os.path.join(root, "PRD.md")
    if not os.path.exists(target):
        return rg.blocked("PRD.md does not exist", "Run: storypole prd build")
    if _strip_stamp(open(target, encoding="utf-8").read()) != _strip_stamp(render(root)):
        return rg.blocked("PRD.md is out of date with features/",
                          "Run: storypole prd build")
    return rg.done("PRD.md is current.")
